[build]
builder = "NIXPACKS"

[deploy]
# Change is here: Run migrations && then start app
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level info"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
